spring:
  application:
    name: data-api
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: ac123456
    driver-class-name: org.postgresql.Driver
kong:
  admin:
    url: http://localhost:8001/