spring:
  application:
    name: data-api
  security:
    oauth2:
      resourceserver:
        jwt:
#          issuer-uri: http://localhost:9080/auth/realms/myrealm
          # jwk-set-uri 可以省略，Spring 会根据 issuer-uri 自动推导
           jwk-set-uri: http://localhost:9080/realms/myrealm/protocol/openid-connect/certs
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: ac123456
    driver-class-name: org.postgresql.Driver
kong:
  admin:
    url: http://localhost:8001/

keycloak:
  realm: myrealm
  auth-server-url: http://localhost:9080/auth
  ssl-required: external
  resource: myclient
  credentials:
    secret: ftHSBVz8KboFk5lIlKsvOKtFnQbhR9X7
  user-resource-role-mappings: true
  public-client: false
  bearer-only: true